### ISSUE TITLE
A list of issues to fix

### ISSUE THREAD

**Issue by amlel-el-mahrouss** [amlel-el-mahrouss/zka#2]
# A list of issues to fix.

## Brief

These are a list of issues to fix right now in the project.

## To-Do

- [ ] Fix scheduler task switch code.
- [ ] Add more runtime guarantees for C++
- [ ] Add a testing framework for the Ne File System. (maybe use D, it has good unit test support.)
- [ ] Add unit testing for the kernel in general. (With a -DZKA_UNIT_TESTING switch)
