### ISSUE TITLE
aarch64 microkernel

### ISSUE THREAD

**Issue by amlel-el-mahrouss** [amlel-el-mahrouss/zka#3]
# aarch64 microkernel

## Brief

Focus on supporting aarch64, x64 and RISC architectures and their common hardware.

## Target

zka, zba, acb, toolchainkit, mdk

## Status

In-Progress

## To-Do List

- [X] Port kernel and bootloader to ARM EFI.
- [ ] Make it run on ACB. with NVRAM vars.
- [ ] Implement fast disk I/O, SMP and networking.
