### ISSUE TITLE
AMD PCnet for NetworkKit.

### ISSUE THREAD

**Issue by amlel-el-mahrouss** [amlel-el-mahrouss/zka#7]
## To-Do

- [ ] Get PCI device and DMA address.
- [ ] Organize TX and RX as buffers as in the PCnet documentation.
- [ ] Get a MVP working. (ping perdu.com)

## Why now?

I forgot about it, and I was focusing on other important aspects of the system.
